spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desires_dev_db?useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 5000
