spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      pool-name: SpringHickariPool
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true